<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-16T07:52:28 IST" name="Default suite" finished-at="2022-12-16T07:52:32 IST" duration-ms="4233">
    <groups>
    </groups>
    <test started-at="2022-12-16T07:52:28 IST" name="Default test" finished-at="2022-12-16T07:52:32 IST" duration-ms="4233">
      <class name="com.employee.Scripts.TestClass">
        <test-method is-config="true" signature="initialization()[pri:0, instance:com.employee.Scripts.TestClass@661972b0]" started-at="2022-12-16T07:52:21 IST" name="initialization" finished-at="2022-12-16T07:52:28 IST" duration-ms="6597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="ValidLoginVerification()[pri:0, instance:com.employee.Scripts.TestClass@661972b0]" started-at="2022-12-16T07:52:28 IST" name="ValidLoginVerification" finished-at="2022-12-16T07:52:30 IST" duration-ms="1951" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidLoginVerification -->
        <test-method signature="ValidHomeVerification()[pri:1, instance:com.employee.Scripts.TestClass@661972b0]" started-at="2022-12-16T07:52:30 IST" name="ValidHomeVerification" finished-at="2022-12-16T07:52:30 IST" duration-ms="755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidHomeVerification -->
        <test-method signature="ValidAddEmpVerification()[pri:2, instance:com.employee.Scripts.TestClass@661972b0]" started-at="2022-12-16T07:52:30 IST" name="ValidAddEmpVerification" finished-at="2022-12-16T07:52:31 IST" duration-ms="143" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Ammu Anil] but found [Anu S]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Ammu Anil] but found [Anu S]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.employee.Scripts.TestClass.ValidAddEmpVerification(TestClass.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidAddEmpVerification -->
        <test-method signature="ValidEmpListVerification()[pri:3, instance:com.employee.Scripts.TestClass@661972b0]" started-at="2022-12-16T07:52:31 IST" name="ValidEmpListVerification" finished-at="2022-12-16T07:52:32 IST" duration-ms="1312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidEmpListVerification -->
      </class> <!-- com.employee.Scripts.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
